[package]
<<<<<<< HEAD
name = "cdisc-cache-invalidator"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.48", features = ["full"] }
chrono = "0.4"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
=======
name = "cdisc-proxy"
version = "0.1.2"
edition = "2024"

[dependencies]
anyhow = "1.0"
axum = "0.8"
hyper = "1.8"
tokio = { version = "1.48", features = ["full"] }
tokio-util = "0.7"
tower-http = { version = "0.6", features = ["timeout"] }
reqwest = { version = "0.12", features = ["json", "gzip", "stream", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
sled = "0.34"
bincode = "1.3"
hyper-util = { version = "0.1", features = ["tokio", "server-graceful"] }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "macros"] }
fred = "10"
futures = "0.3"
tracing = "0.1"
tracing-subscriber = "0.3"
humantime = "2.3"
async-trait = "0.1"
tokio-stream = "0.1"
dashmap = "6.1"
scopeguard = "1.2"
url = "2.5"
percent-encoding = "2.3"

[dev-dependencies]
tower = "0.5"
http = "1"
hyper = "1.8"
axum-extra = "0.9"
>>>>>>> rustproxy
